
version: '3'
services:
  app:
    container_name: backend_aws
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    container_name: database_mogo
    image: mongo
    volumes:
      - './data:/data/db'
    ports:
      - 27017:27017      